# -*- coding: utf-8 -*-
"""Project-98.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YMk6ifSZMdVusczrXuRnubFY98Ly3sn-
"""

file1 = open("Test1.txt", "r+")
file2 = open("Test2.txt", "r+")

test1 = file1.read()
test2 = file2.read()

file1.truncate(0)
file1.write(test2)
file1.close

file2.truncate(0)
file2.write(test1)
file2.close

print("replaced")